trigger: none

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

jobs:
- template: ../../eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: search
    MaxParallel: 2
    EnvVars:
      # Variables set at queue-time don't seem to persist as environment variables in templates.
      AZURE_SEARCH_TEST_VERBOSE: $(AZURE_SEARCH_TEST_VERBOSE)
      AZURE_SEARCH_TEST_MODE: Live
